<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>PCFishController</AssemblyName>
    <RootNamespace>PCFishController</RootNamespace>
    <Version>0.25.0</Version>
    <ApplicationIcon>pcfish-terry.ico</ApplicationIcon>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <!-- 只生成一个 exe，双击就能跑 -->
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>none</DebugType>
  </PropertyGroup>

</Project>
