namespace PCFishController;

internal static class UiLanguage
{
    private static readonly Dictionary<string, string> English = new(StringComparer.Ordinal)
    {
        ["PCFish助手"] = "PCFish Assistant",
        ["繁育 · 仓库 · 鱼缸"] = "Breeding · Warehouse · Tank",
        ["本地连接  ·  后台运行"] = "Local bridge · Background mode",
        ["◇   概览"] = "◇   Overview",
        ["♥   自动繁育"] = "♥   Auto Breeding",
        ["▣   自动合成"] = "▣   Auto Synthesis",
        ["▤   仓库"] = "▤   Warehouse",
        ["◇   合成路线"] = "◇   Synthesis Route",
        ["♣   图鉴 / 目标"] = "♣   Collection / Goals",
        ["≡   日志"] = "≡   Logs",
        ["⚙   设置"] = "⚙   Settings",
        ["命令"] = "Command",
        ["输入 /setting 打开设置命令"] = "Type /setting to open the settings command",
        ["执行"] = "Run",
        ["输入 /setting 或 /设置，直接跳到本页的设置项；输入 /help 查看可用命令。"] = "Type /setting to jump to these options, or /help to list available commands.",
        ["已打开设置"] = "Settings opened",
        ["/setting 打开设置　/help 查看命令"] = "/setting open settings   /help list commands",
        ["未知命令："] = "Unknown command: ",
        ["请输入命令，例如 /setting"] = "Enter a command, for example /setting",
        ["启动时与每小时自动检查更新"] = "Check for updates at startup and hourly",
        ["免责声明"] = "Disclaimer",
        ["TBH助手免费下载和使用。Awan维护代码已在 GitHub 开源。"] = "TBH Assistant is free to download and use. Awan maintains the open-source code on GitHub.",
        ["请从官方发布页下载；遇到收费售卖，请勿付款，并先核验版本。"] = "Download from the official Releases page. Do not pay sellers; verify the version first.",
        ["自动化操作可能受到游戏或平台规则限制，请先阅读相关规则并自行评估账号风险。"] = "Automation may be limited by game or platform rules. Read the rules and assess account risks before use.",
        ["QQ群：123777707 · 验证答案：挂机助手"] = "QQ Group: 123777707 · Verification: 挂机助手",
        ["GitHub"] = "GitHub",
        ["QQ群"] = "QQ Group",
        ["赞助"] = "Sponsor",
        ["打开链接失败："] = "Could not open link: ",
        ["查询市场价"] = "Fetch Market Prices",
        ["Steam 最低价"] = "Steam Low",
        ["正在查询 Steam 市场报价…"] = "Fetching Steam market prices…",
        ["未查询市场价：点「查询市场价」获取 Steam 参考价。"] = "No market prices loaded. Click Fetch Market Prices to get Steam reference prices.",
        ["市场价："] = "Market: ",
        [" 条报价，更新于 "] = " quotes, updated ",
        ["无报价"] = "No listing",
        ["查询失败："] = "Fetch failed: ",
        ["已获取 "] = "Loaded ",
        [" 条 Steam 市场报价。"] = " Steam market quotes.",
        ["Steam 市场查询失败："] = "Steam market fetch failed: ",
        ["Steam 市场没有返回可识别的报价。"] = "Steam market returned no recognizable quotes.",
        ["Steam 市场返回失败，稍后再试。"] = "Steam market request failed; try again later.",
        ["已读取 "] = "Loaded ",
        [" 条报价…"] = " quotes…",
        ["初始化中"] = "Initializing",
        ["环境未就绪"] = "Environment not ready",
        ["重新检测"] = "Re-check",
        ["初始化中：正在检测游戏运行环境和插件…"] = "Initializing: checking the game runtime and plugin…",
        ["运行环境检测未通过："] = "Environment check failed: ",
        ["运行环境仍未就绪："] = "Environment still not ready: ",
        ["PCFish 助手 · 初始化"] = "PCFish Assistant · Startup",
        ["是否现在执行一键部署来修好它？"] = "Run One-Click Setup now to fix it?",
        ["修好后点「重新检测」，助手才会连接游戏。"] = "After fixing it, click Re-check so the assistant can connect.",
        ["修好之后点「是」重新检测；点「否」则暂不连接游戏。"] = "Click Yes to re-check after fixing, or No to stay disconnected for now.",
        ["之后也可以随时点「重新检测」。"] = "You can click Re-check again at any time.",
        ["初始化未通过："] = "Startup check failed: ",
        ["。点「重新检测」，或到「设置 → 一键部署」修复。"] = ". Click Re-check, or fix it under Settings → One-Click Setup.",
        ["运行环境尚未就绪，暂不合成。"] = "The environment is not ready; synthesis is on hold.",
        ["已开启自动检查更新。"] = "Automatic update checks enabled.",
        ["已关闭自动检查更新。"] = "Automatic update checks disabled.",
        ["PCFish 助手有新版本"] = "PCFish Assistant Update",
        ["检查更新"] = "Check for Updates",
        ["概览"] = "Overview",
        ["一键开启"] = "Start All",
        ["全部关闭"] = "Stop All",
        ["正在运行"] = "Running",
        ["已停止"] = "Stopped",
        ["已暂停"] = "Paused",
        ["等待连接"] = "Waiting",
        ["正在开启"] = "Starting",
        ["已设置 BepInEx 控制台默认隐藏"] = "BepInEx console is hidden by default",
        ["已隐藏游戏的 BepInEx 控制台"] = "Game BepInEx console hidden",
        ["自动繁育"] = "Auto Breeding",
        ["仓库"] = "Warehouse",
        ["合成路线"] = "Synthesis Route",
        ["图鉴 / 目标"] = "Collection / Goals",
        ["日志"] = "Logs",
        ["设置"] = "Settings",
        ["游戏连接、鱼群和繁育状态"] = "Game, stock and breeding status",
        ["控制检查周期和繁育条件"] = "Set the check interval and breeding rules",
        ["查看鱼群、繁育次数与冷却时间"] = "View fish, breed uses and cooldowns",
        ["根据 Wiki 配方查看材料状态并设置繁育目标"] = "View Wiki ingredients and set breeding goals",
        ["查看已发现鱼种，设置最终目标和繁育路线"] = "View discovered species and set a target route",
        ["查看助手和游戏桥接的运行记录"] = "View assistant and game bridge logs",
        ["管理助手语言和窗口行为"] = "Set language and window behavior",
        ["管理助手语言、窗口行为和命令"] = "Set language, window behavior and commands",
        ["一键部署"] = "One-Click Setup",
        ["一次点击完成运行前的全部准备：安装 BepInEx 运行环境、放入插件、生成并打开游戏内的动作总闸。"] =
            "Prepares everything in one click: installs the BepInEx runtime, places the plugin, and turns on the in-game action switch.",
        ["游戏目录"] = "Game folder",
        ["留空自动查找，例如 D:\\SteamLibrary\\steamapps\\common\\PC FISH"] = "Leave empty to auto-detect, e.g. D:\\SteamLibrary\\steamapps\\common\\PC FISH",
        ["浏览…"] = "Browse…",
        ["选择包含 PCFish.exe 的游戏目录"] = "Select the game folder that contains PCFish.exe",
        ["版本更新"] = "Version Update",
        ["正在准备…"] = "Preparing…",
        ["一键部署失败："] = "Setup failed: ",
        ["检查更新"] = "Check for Updates",
        ["立即更新"] = "Update Now",
        ["打开发布页"] = "Open Releases",
        ["更新只替换程序文件，不会动你的配置和游戏数据。"] = "Updating only replaces program files; your settings and game data stay untouched.",
        ["正在检查更新…"] = "Checking for updates…",
        ["这个发布没有可下载的压缩包，请到发布页手动下载。"] = "This release has no downloadable archive. Please download it from the releases page.",
        ["确认更新"] = "Confirm Update",
        ["鱼群总数"] = "Fish in warehouse",
        ["可繁育"] = "Breedable",
        ["繁育计数器"] = "Breeding counter",
        ["鱼缸等级"] = "Tank level",
        ["▏ 当前状态"] = "▏ Current Status",
        ["▏ 快捷操作"] = "▏ Quick Actions",
        ["▏ 下一轮"] = "▏ Next Check",
        ["立即繁育一轮"] = "Breed Now",
        ["检查鱼缸升级"] = "Check Tank Upgrade",
        ["刷新鱼群数据"] = "Refresh Fish Data",
        ["自动运行"] = "Automation",
        ["自动繁育"] = "Auto Breeding",
        ["每轮后检查升级"] = "Check Upgrade After Each Round",
        ["检查间隔（分钟，随机）"] = "Check Interval (random minutes)",
        ["至"] = "to",
        ["最低稀有度（0 为不限）"] = "Minimum Rarity (0 = any)",
        ["▣   自动合成"] = "▣   Auto Synthesis",
        ["自动合成"] = "Auto Synthesis",
        ["仓库超过阈值时自动合并，排除赛季鱼与配方鱼"] = "Merges automatically above the threshold, excluding season and recipe fish",
        ["排除赛季鱼与配方鱼"] = "Exclude season and recipe fish",
        ["触发阈值（仓库鱼数）"] = "Trigger threshold (fish count)",
        ["合成后安全等待（秒）"] = "Safety wait after craft (seconds)",
        ["每次合并 10 条；优先使用 0 繁育次数、稀有度最低的鱼。"] = "Each craft takes 10 fish, preferring zero breed uses and the lowest rarity.",
        ["立即合成一次"] = "Synthesize Once Now",
        ["合成相关的阈值和等待时间已移到「自动合成」页面。"] = "Synthesis thresholds and wait times now live on the Auto Synthesis page.",
        ["仓库：等待鱼群数据…"] = "Warehouse: waiting for fish data…",
        ["候选：等待鱼群数据…"] = "Candidates: waiting for fish data…",
        ["忽略阈值，直接挑 10 条合成一次；需先 ARM 并与桥接保持连接。"] = "Ignores the threshold and crafts 10 fish once. ARM and an active bridge are required.",
        ["自动合成（仓库超过该数量时启用）"] = "Auto Synthesis (enabled above this stock size)",
        ["排除赛季鱼与赛季配方鱼，优先使用 0 繁育次数和低稀有度的鱼。"] = "Excludes season fish and season recipe fish, and prefers fish with no breed uses left, lowest rarity first.",
        ["每次检查会使用现有繁育计数器，优先选择目标路线、高稀有度且已结束冷却的鱼。"] = "Each check uses available breeding counters and prioritizes goal-route, high-rarity fish whose cooldown has ended.",
        ["手动控制"] = "Manual Controls",
        ["ARM（放行动作）"] = "ARM (Allow Actions)",
        ["查询计数器状态"] = "Refresh Counter Status",
        ["动作需游戏内放行，并与桥接保持连接。"] = "Actions require game permission and an active bridge connection.",
        ["我的鱼"] = "My Fish",
        ["搜索鱼种或 ID"] = "Search species or ID",
        ["全部"] = "All",
        ["冷却中"] = "Cooling Down",
        ["次数用尽"] = "Breed Uses Exhausted",
        ["锁定/展示"] = "Locked / Displayed",
        ["稀有度优先"] = "Rarity First",
        ["星级优先"] = "Stars First",
        ["次数优先"] = "Uses First",
        ["冷却最快"] = "Soonest Cooldown",
        ["价格降序"] = "Price High to Low",
        ["价格升序"] = "Price Low to High",
        ["刷新仓库"] = "Refresh Warehouse",
        ["鱼种"] = "Species",
        ["稀有度"] = "Rarity",
        ["星级"] = "Stars",
        ["剩余繁育"] = "Breed Uses Left",
        ["冷却 CD"] = "Cooldown",
        ["状态"] = "Status",
        ["等级"] = "Level",
        ["鱼 ID"] = "Fish ID",
        ["Wiki 合成路线"] = "Wiki Synthesis Route",
        ["路线目标"] = "Route Target",
        ["设为繁育目标"] = "Set Breeding Goal",
        ["刷新仓库状态"] = "Refresh Fish Data",
        ["刷新 Wiki 数据"] = "Refresh Wiki Data",
        ["当前路线"] = "Current Route",
        ["仓库同步"] = "Warehouse synced",
        ["仓库同步："] = "Warehouse sync: ",
        ["缺少数量"] = "Missing quantity",
        ["数量达标"] = "Quantity met",
        ["自动操作已暂停："] = "Automation paused: ",
        ["等待游戏空闲…"] = "Waiting for the game to be idle…",
        ["正在核对服务器繁育次数…"] = "Checking breeding counts with the server…",
        ["服务器次数用尽"] = "No server breed uses",
        ["服务器未找到"] = "Not found on server",
        ["服务器次数核对失败，点击 ARM 重新核对"] = "Server count check failed. Click ARM to retry.",
        ["服务器次数核对失败，稍后自动重试"] = "Server count check failed; retrying automatically",
        ["服务器次数核对超时，稍后自动重试"] = "Server count check timed out; retrying automatically",
        ["本笔结果未知，等待游戏回包后点击 ARM 恢复"] = "Result unknown. Wait for the game response, then click ARM to resume.",
        ["请求或收尾失败，确认游戏恢复后点击 ARM 继续"] = "Request or completion failed. Confirm the game has recovered, then click ARM to resume.",
        ["等待游戏数据"] = "Waiting for game data",
        ["黄色：材料不足　蓝色：数量达标　绿色：可合成"] = "Yellow: missing ingredients   Blue: quantity met   Green: ready to synthesize",
        ["路线鱼"] = "Route Fish",
        ["数量"] = "Required",
        ["用途"] = "Role",
        ["图鉴"] = "Collection",
        ["可用 / 拥有"] = "Usable / Owned",
        ["来源"] = "Source",
        ["合成路线"] = "Synthesis Route",
        ["繁育路线"] = "Breeding Route",
        ["目标"] = "Goal",
        ["目标鱼种图鉴"] = "Target Species Collection",
        ["全部鱼种"] = "All Species",
        ["已解锁鱼种"] = "Unlocked Species",
        ["未解锁鱼种"] = "Locked Species",
        ["显示分类"] = "Filter",
        ["目标鱼种"] = "Target Species",
        ["目标星级"] = "Target Stars",
        ["按目标路线优先"] = "Prioritize Goal Route",
        ["我的图鉴与最终目标"] = "Collection and Final Goal",
        ["界面语言"] = "Interface Language",
        ["简体中文"] = "简体中文",
        ["语言会立即应用到助手界面。"] = "The selected language applies immediately.",
        ["关闭助手时选择退出，或缩小到系统托盘继续运行。"] = "When closing the window, choose Exit or minimize to the system tray.",
        ["关闭窗口时可退出助手，或缩小到系统托盘继续运行。"] = "Choose Exit or minimize to the system tray when closing the window.",
        ["请选择退出助手、缩小到系统托盘，或取消返回。"] = "Choose Exit, minimize to the system tray, or cancel to return.",
        ["确定要关闭 PCFish 助手吗？"] = "What would you like to do with PCFish Assistant?",
        ["关闭 PCFish 助手"] = "Close PCFish Assistant",
        ["PCFish 助手"] = "PCFish Assistant",
        ["打开助手"] = "Open Assistant",
        ["退出助手"] = "Exit Assistant",
        ["缩小到托盘"] = "Minimize to Tray",
        ["取消"] = "Cancel",
        ["助手已缩小到系统托盘。"] = "PCFish Assistant is running in the system tray.",
        ["运行中"] = "Running",
        ["未运行"] = "Not Running",
        ["已连接"] = "Connected",
        ["未连接"] = "Disconnected",
        ["匹配"] = "Matched",
        ["待更新"] = "Update Required",
        ["正在重试"] = "Retrying",
        ["是"] = "Yes",
        ["否"] = "No",
        ["基础"] = "Basic",
        ["普通"] = "Common",
        ["高级"] = "Advanced",
        ["稀有"] = "Rare",
        ["传说"] = "Legendary",
        ["神话"] = "Mythic",
        ["金鱼"] = "Goldfish",
        ["阳光豆娘鱼"] = "Sunshine Tang",
        ["紫罗兰拟雀鲷"] = "Violet Dottyback",
        ["蓝宝石雀鲷"] = "Sapphire Chromis",
        ["烈焰蝶尾金鱼"] = "Flame Fantail",
        ["霜鳞太阳鱼"] = "Frostblue Sunfish",
        ["樱桃鲃"] = "Cherry Barb",
        ["月角豆娘鱼"] = "Moonhorn Tang",
        ["苔背小精灵"] = "Mossback Otocinclus",
        ["霓虹清洁隆头鱼"] = "Neon Cleaner Wrasse",
        ["三色锦鲤"] = "Calico Koi",
        ["火鳍兵鲷"] = "Emberfin Snapper",
        ["睡衣雀鲷"] = "Pajama Cardinalfish",
        ["泻湖雀鲷"] = "Lagoon Chromis",
        ["铜带蝴蝶鱼"] = "Copperband Butterflyfish",
        ["绯红雀鲷"] = "Crimson Cardinalfish",
        ["星鳍邦盖拟雀鲷"] = "Banggai Starfin",
        ["黄金蝴蝶鱼"] = "Golden Butterflyfish",
        ["霓虹条纹灯鱼"] = "Neon Streak Tetra",
        ["棱镜虹鱼"] = "Prism Rainbowfish",
        ["奶油泡芙河豚"] = "Cream Puff Puffer",
        ["红脸火焰虾虎鱼"] = "Blushing Firefish",
        ["金尾帝王鱼"] = "Royal Goldtail",
        ["天翼飞鱼"] = "Skywing Flying Fish",
        ["宝石花鮨"] = "Jewel Mandarinfish",
        ["珊瑚小丑鱼"] = "Coral Clownfish",
        ["黄金海马"] = "Golden Seahorse",
        ["黄金长鳍蝴蝶鱼"] = "Golden Moorish Idol",
        ["小蓝鲸"] = "Little Blue Whale",
        ["绯红皇冠蓑鲉"] = "Crimson Crown Lionfish",
        ["紫水晶斗鱼"] = "Amethyst Betta",
        ["蓝电金枪鱼"] = "Bluebolt Tuna",
        ["旭日兰寿"] = "Sunburst Ranchu",
        ["霜蓝翻车鱼"] = "Frostblue Sunfish",
        ["青柠背海龟"] = "Limeback Sea Turtle",
        ["祭典章鱼"] = "Matsuri Octopus",
        ["每轮后检查升级"] = "Check Upgrade After Each Round",
        ["检查鱼缸升级"] = "Check Tank Upgrade",
        ["已开"] = "On",
        ["已关"] = "Off",
        ["目标优先"] = "Goal Priority",
        ["稀有度优先"] = "Rarity Priority",
        ["繁育充能"] = "Breeding charge",
        ["繁育计数器"] = "Breeding counter",
        ["鱼缸等级"] = "Tank level",
        ["鱼缸："] = "Tank: ",
        ["鱼群："] = "Fish: ",
        ["稀有度分布："] = "Rarity: ",
        ["繁育计数器："] = "Breeding counter: ",
        ["下一颗心约"] = "Next counter in about ",
        ["分钟后"] = " min",
        ["已满"] = "Full",
        ["格"] = "slots",
        ["游戏进程："] = "Game process: ",
        ["桥接连接："] = "Bridge: ",
        ["可繁育最高稀有度："] = "Highest breedable rarity: ",
        ["目标图鉴："] = "Target collection: ",
        ["已解锁"] = "Unlocked",
        ["未解锁"] = "Locked",
        ["关闭按钮"] = "On Close",
        ["每次询问"] = "Ask Every Time",
        ["直接退出助手"] = "Exit Assistant Directly",
        ["缩小至托盘"] = "Minimize to System Tray",
        ["点击右上角 X 时按此设置执行，选择后自动保存。托盘模式下助手继续运行。"] = "Choose what X does. Your choice is saved automatically. The assistant keeps running in tray mode.",
        ["目标鱼种："] = "Target species: ",
        ["图鉴状态："] = "Collection status: ",
        ["目标星级："] = "Target stars: ",
        ["仓库数量："] = "Owned: ",
        ["仓库最高星级："] = "Highest owned stars: ",
        ["解锁来源：鱼种图鉴或仓库已有该鱼"] = "Unlock source: discovered or present in warehouse",
        ["解锁来源：发现该鱼种后自动更新"] = "Unlock source: updates when discovered",
        ["已拥有图鉴"] = "Collection Status",
        ["赛季配方"] = "Season recipe",
        ["已拥有"] = "Owned",
        ["材料不足"] = "Missing ingredients",
        ["材料未齐"] = "Ingredients missing",
        ["可合成"] = "Ready to synthesize",
        ["材料齐全"] = "Ingredients ready",
        ["缺少材料"] = "Missing ingredients",
        ["可先合成"] = "Can synthesize first",
        ["已备齐"] = "Ready",
        ["Wiki 配方"] = "Wiki recipe",
        ["待验证"] = "Unverified",
        ["不可繁育"] = "Not breedable",
        ["可用"] = "usable",
        ["拥有"] = "owned",
        ["目标鱼"] = "Target fish",
        ["核心鱼"] = "Core fish",
        ["辅助鱼"] = "Support fish",
        ["上一星级"] = "Previous star",
        ["常规合成配方待验证"] = "Regular synthesis recipe unverified",
        ["请选择鱼种。"] = "Select a species.",
        ["冷却未知"] = "Cooldown unknown",
        ["展示中"] = "Displayed",
        ["已锁定"] = "Locked",
        ["就绪"] = "Ready",
        ["次数用尽"] = "Uses exhausted",
        ["显示 "] = "Showing ",
        [" 条"] = " fish",
        ["等待游戏数据…"] = "Waiting for game data…",
        ["等待游戏数据..."] = "Waiting for game data...",
        ["重新整理仓库"] = "Refresh Warehouse",
        ["所有鱼种"] = "All species",
        ["立即检查"] = "Check now",
        ["最大合成"] = "Merge limit",
        ["可繁育最高稀有度"] = "Highest breedable rarity",
        ["已发现 "] = "Discovered ",
        [" 种　当前仓库 "] = " species   Warehouse: ",
        [" 经验 "] = "   EXP ",
        ["等级="] = "Level=",
        [" 经验="] = " EXP=",
        ["总数="] = "Total=",
        ["可繁殖="] = "Breedable=",
        ["次数耗尽="] = "Exhausted=",
        ["合成上限="] = "Merge limit=",
        ["鱼群总数 "] = "Fish total ",
        ["可繁育 "] = "Breedable ",
        ["次数耗尽 "] = "Exhausted ",
        ["合成上限 "] = "Merge limit ",
        ["版本="] = "Version=",
        ["放行="] = "Allowed=",
        ["累计动作="] = "Actions=",
        ["ARM="] = "ARM=",
        ["内存 "] = "Memory ",
        ["繁育"] = "Breeding",
        ["升级"] = "Upgrade",
        ["亲鱼"] = "Parents",
        ["请求"] = "Request",
        ["失败"] = "failed",
        ["成功"] = "succeeded",
        ["本轮"] = "This round",
        ["计数器"] = "counter",
        ["次数"] = "uses",
        ["冷却"] = "Cooldown",
        ["鱼缸"] = "Tank",
        ["操作间隔"] = "Action interval",
        ["最小动作间隔"] = "Minimum action interval",
        ["桥接版本"] = "Bridge version",
        ["桥接未连接"] = "Bridge disconnected",
        ["请求失败"] = "Request failed",
        ["等待"] = "Waiting",
        ["读取"] = "Read",
        ["显示"] = "Shown",
        ["刷新"] = "Refresh",
        ["手动触发"] = "Manual trigger",
        ["已解除"] = "Released",
        ["暂时不可升级"] = "Upgrade currently unavailable",
        ["经验"] = "EXP",
        ["超时"] = "Timeout",
        ["无需继续"] = "No further action needed",
        ["状态："] = "Status: ",
        ["总数 "] = "Total ",
        ["可繁育最高稀有度："] = "Highest breedable rarity: ",
        ["目标鱼图鉴："] = "Target collection: ",
        ["目标鱼种图鉴"] = "Target Species Collection",
        ["Synthesis materials"] = "Synthesis materials",
        ["未知鱼"] = "Unknown fish",
        ["冷却未知"] = "Cooldown unknown",
        ["已关闭自动升级。"] = "Automatic upgrade disabled.",
        ["已开启：每轮繁育结束后自动检查鱼缸升级。"] = "Automatic tank upgrade check enabled after each breeding round.",
        ["已开启自动繁育，连接就绪后立即检查繁育计数器。"] = "Auto breeding enabled. The counter will be checked when the bridge connects.",
        ["已取消自动繁育，同时解除 ARM。"] = "Auto breeding disabled and ARM released.",
        ["手动触发：开始一轮繁育。"] = "Manual start: beginning a breeding round.",
        ["手动请求鱼缸升级检查。"] = "Manual tank upgrade check requested.",
        ["请求完整鱼群清单。"] = "Requesting the full fish inventory.",
        ["桥接未连接，跳过。"] = "Bridge disconnected; request skipped.",
        ["请求读取游戏繁育计数器状态。"] = "Requesting the in-game breeding counter.",
        ["游戏数据还没就绪（可能还在读档）"] = "Game data is not ready yet. The game may still be loading.",
        ["开始检查繁育计数器与可繁育亲鱼。"] = "Checking breeding counters and available parents.",
        ["本轮无需继续繁育。"] = "No more breeding is needed this round.",
        ["稍后改选其他鱼再试一次。"] = "Another fish pair will be tried later.",
        ["请求很快被拒绝，这对鱼暂时跳过 2 小时。"] = "The request was rejected. This pair will be skipped for 2 hours.",
        ["请求等待较久才失败，可能遇到网络超时；这对鱼暂时跳过 45 分钟。"] = "The request timed out. This pair will be skipped for 45 minutes.",
        ["本轮失败已达上限，停止重试。"] = "The retry limit for this round was reached.",
        ["繁育回包报告成功："] = "Breed response succeeded: ",
        ["繁育请求失败（"] = "Breed request failed (",
        ["发起繁育（"] = "Starting breed (",
        ["目标优先："] = "goal priority: ",
        ["稀有度优先："] = "rarity priority: ",
        ["繁育核实成功："] = "Breed verified: ",
        ["等待鱼群核实。"] = "Waiting to verify the fish inventory.",
        ["鱼缸等级 "] = "Tank level ",
        ["满足升级条件；等待动作间隔后升级。"] = "meets the upgrade requirement; waiting for the action interval.",
        ["游戏判定暂不可升级。"] = "The game reports that an upgrade is unavailable.",
        ["结果页已关闭"] = "Result panel closed",
        ["可繁育鱼"] = "Breedable fish",
        ["合成材料"] = "Synthesis materials",
        ["只读"] = "Read-only",
        ["已开启"] = "Enabled",
        ["已关闭"] = "Disabled",
        ["未知"] = "Unknown",
        ["无"] = "None",
        ["目标图鉴：请选择目标鱼种"] = "Target collection: choose a species",
        ["请选择目标鱼种后查看解锁状态、仓库数量和星级进度。"] = "Choose a species to see unlock status, owned quantity and star progress.",
        ["鱼缸升级"] = "Tank Upgrade",
        ["等待繁育回包…"] = "Waiting for breeding response…",
        ["回包较慢，正在自动核对本笔繁育结果"] = "Response delayed; automatically checking this breeding request",
        ["连接中断，正在自动核对本笔繁育结果"] = "Connection lost; automatically checking this breeding request",
        ["本笔已结束，等待网络恢复后重新核对"] = "Request finished; waiting to recheck after network recovery",
        ["游戏接口或收尾异常："] = "Game API or completion error: ",
        ["本笔鱼群变化未核实，请检查游戏状态"] = "Fish changes could not be verified; check the game",
        ["本轮繁育中…"] = "Breeding round in progress…",
        ["即将检查…"] = "Checking soon…",
        ["解除 ARM"] = "Disarm",
        ["窗口自检通过 "] = "Window self-check passed ",
        [" 次"] = " checks",
        ["窗口自检已锁停"] = "Window self-check paused actions",
        ["Wiki Season 1：已确认材料和星级要求；赛季鱼使用合成路线。"] = "Wiki Season 1: Ingredients and star requirements are confirmed; seasonal fish use synthesis routes.",
        ["Wiki：普通合成固定物种配方和当前概率未发布；请使用繁育路线优先积累目标相关鱼。"] = "Wiki: Fixed-species recipes and current probabilities for regular synthesis are unpublished; use the breeding route to build toward the target fish.",
        ["未设置"] = "Not set",
        ["已发现"] = "Discovered",
    };

    private static readonly Dictionary<string, string> Chinese = English
        .GroupBy(pair => pair.Value, StringComparer.Ordinal)
        .ToDictionary(group => group.Key, group => group.First().Key, StringComparer.Ordinal);
    private static readonly HashSet<string> StandaloneOnly = new(StringComparer.Ordinal)
        { "是", "否", "无", "格", "至" };

    internal static string Current { get; private set; } = "zh";
    internal static bool IsEnglish => Current == "en";

    internal static void Set(string language)
        => Current = string.Equals(language, "en", StringComparison.OrdinalIgnoreCase) ? "en" : "zh";

    internal static string T(string text)
    {
        if (string.IsNullOrEmpty(text)) return text ?? "";
        return ConvertFrom(text, "zh");
    }

    private static string ConvertFrom(string text, string sourceLanguage)
    {
        if (string.IsNullOrEmpty(text) || (sourceLanguage == "en") == IsEnglish) return text ?? "";
        var table = IsEnglish ? English : Chinese;
        if (table.TryGetValue(text, out var exact)) return exact;
        foreach (var pair in table.OrderByDescending(x => x.Key.Length))
        {
            if (StandaloneOnly.Contains(pair.Key) && !string.Equals(text, pair.Key, StringComparison.Ordinal))
                continue;
            if (text.Contains(pair.Key, StringComparison.Ordinal))
                text = text.Replace(pair.Key, pair.Value, StringComparison.Ordinal);
        }
        return text;
    }

    internal static void Apply(Control root, string sourceLanguage)
    {
        if (root is ToolStrip strip)
        {
            foreach (ToolStripItem item in strip.Items) ApplyToolStripItem(item, sourceLanguage);
        }
        else if (root is DataGridView grid)
        {
            foreach (DataGridViewColumn column in grid.Columns) column.HeaderText = ConvertFrom(column.HeaderText, sourceLanguage);
            foreach (DataGridViewRow row in grid.Rows)
                foreach (DataGridViewCell cell in row.Cells)
                    if (cell.Value is string value) cell.Value = ConvertFrom(value, sourceLanguage);
        }
        else if (root is ComboBox combo)
        {
            if (combo.DataSource == null)
            {
                var selected = combo.SelectedIndex;
                for (var i = 0; i < combo.Items.Count; i++)
                    if (combo.Items[i] is string item) combo.Items[i] = ConvertFrom(item, sourceLanguage);
                if (selected >= 0 && selected < combo.Items.Count) combo.SelectedIndex = selected;
                combo.Text = ConvertFrom(combo.Text, sourceLanguage);
            }
        }
        else
        {
            root.Text = ConvertFrom(root.Text, sourceLanguage);
            if (root is TextBox textBox)
                textBox.PlaceholderText = ConvertFrom(textBox.PlaceholderText, sourceLanguage);
        }
        foreach (Control child in root.Controls) Apply(child, sourceLanguage);
    }

    private static void ApplyToolStripItem(ToolStripItem item, string sourceLanguage)
    {
        item.Text = ConvertFrom(item.Text, sourceLanguage);
        if (item is ToolStripDropDownItem dropDown)
            foreach (ToolStripItem child in dropDown.DropDownItems)
                ApplyToolStripItem(child, sourceLanguage);
    }
}
